CREATE DATABASE NWKIT;
USE NWKIT;

CREATE TABLE CUSTOMER
(
CID INTEGER PRIMARY KEY,
FName CHAR(20),
LName CHAR(20),
EMail CHAR(50),
Address CHAR(100),
CStatus CHAR(20),
Phone CHAR(20)
);

insert into customer values(123,"Dev",''singh","hk@yahoo.com","ftguyhjaksdf 521sdf","Silver",456789123);
create table login
(
EMail char(50) primary key,
password char(50),
FOREIGN KEY(EMail) REFERENCES CUSTOMER(EMail)

)


CREATE TABLE SILVER_AND_ABOVE
(
CID INTEGER PRIMARY KEY,
CreditLine INTEGER,
FOREIGN KEY(CID) REFERENCES CUSTOMER(CID)

);

CREATE TABLE CREDIT_CARD
(
CCNumber INTEGER PRIMARY KEY,
SecNumber INTEGER,
OwnerName CHAR(40),
CCType CHAR(20),
CCAddress CHAR(100),
ExpDate DATE
);

CREATE TABLE PRODUCT
(
PID INTEGER PRIMARY KEY,
PType CHAR(20),
PName CHAR(20),
PPrice INTEGER,
Description CHAR(100),
PQuantity INTEGER
);

CREATE TABLE OFFER_PRODUCT
(
PID INTEGER PRIMARY KEY,
OfferPrice INTEGER,
FOREIGN KEY(PID) REFERENCES PRODUCT(PID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMPUTER
(
PID INTEGER PRIMARY KEY,
CPUType CHAR(20),
FOREIGN KEY(PID) REFERENCES PRODUCT(PID)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PRINTER
(
PID INTEGER PRIMARY KEY,
PrinterType CHAR(20),
Resolution CHAR(20),
FOREIGN KEY(PID) REFERENCES PRODUCT(PID)

);

CREATE TABLE LAPTOP
(
PID INTEGER PRIMARY KEY,
BType CHAR(20),
Weight INTEGER,
FOREIGN KEY(PID) REFERENCES COMPUTER(PID)

);

CREATE TABLE STORED_CARD
(
CCNumber INTEGER PRIMARY KEY,
CID INTEGER,
FOREIGN KEY(CID) REFERENCES CUSTOMER(CID)
,
FOREIGN KEY(CCNumber) REFERENCES CREDIT_CARD(CCNumber)

);

CREATE TABLE SHIPPING_ADDRESS
(
CID INTEGER,
SAName CHAR(20),
ReceipientName CHAR(40),
Street CHAR(20),
SNumber INTEGER,
City CHAR(20),
Zip INTEGER,
State CHAR(30),
Country CHAR(30),
PRIMARY KEY(CID,SAName),
FOREIGN KEY(CID) REFERENCES CUSTOMER(CID)

);

CREATE TABLE CART
(
CartID INTEGER PRIMARY KEY,
CID INTEGER,
SAName CHAR(20),
CCNumber INTEGER,
TStatus CHAR(20),
TDate DATE,
FOREIGN KEY(CID,SAName) REFERENCES SHIPPING_ADDRESS(CID,SAName)
,
FOREIGN KEY(CCNumber) REFERENCES CREDIT_CARD(CCNumber)

);

CREATE TABLE APPEARS_IN
(
CartID INTEGER,
PID INTEGER,
Quantity INTEGER,
PriceSold INTEGER,
PRIMARY KEY(CartID,PID),
FOREIGN KEY(CartID) REFERENCES CART(CartID)
,
FOREIGN KEY(PID) REFERENCES PRODUCT(PID)

);









